version: "3.9"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  prometheus_data:

services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: go-social/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: go_social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    image: go-social/redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data
    restart: always
  
  prometheus:
    build:
      context: prometheus
      dockerfile: Dockerfile
    image: go-social/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network
    volumes:
      - prometheus_data:/prometheus
    restart: always
  
  backend:
    build:
        context: backend
        dockerfile: Dockerfile
    image: go-social/backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
