version: "3.9"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    # build:
    #   context: postgres
    #   dockerfile: Dockerfile
    image: go-social/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: go_social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  backend:
    # build:
      #   context: backend
      #   dockerfile: Dockerfile
    image: go-social/backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
